"""M8 task 11.2 — performance baseline.

For each baseline corpus entry the test:

  1. Runs the CLI ``N_PERF_RUNS`` times and takes the median wall-clock.
  2. Asserts the median is ≤ ``committed_p50 * TOLERANCE_FACTOR``.

The committed reference values live in ``tests/hardening/baselines/runtime_envelope.json``
(generated by ``tests/hardening/rebaseline.py``).  If the file is absent the
tests are skipped with reason ``baseline_missing``.
"""

from __future__ import annotations

import os
import subprocess
import sys
import time
from pathlib import Path
from statistics import median

import pytest

from tests.adversarial.conftest import CorpusEntry
from tests.hardening.conftest import BASELINE_CORPUS, load_runtime_envelope

pytestmark = pytest.mark.slow

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

N_PERF_RUNS = 5
# Tolerance is read from the committed baseline file (tolerance.wall_clock_pct).
# Fallback of 50 % is only used when the key is absent (e.g. legacy baselines).
_TOLERANCE_FALLBACK_PCT = 50

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_SRC = Path(__file__).resolve().parents[2] / "src"


def _wall_clock_run(args: list[str]) -> float:
    """Return wall-clock seconds for a single CLI invocation."""
    env = {**os.environ, "PYTHONPATH": str(_SRC)}
    t0 = time.monotonic()
    subprocess.run(
        [sys.executable, "-m", "mempalace_migrator.cli.main", *args],
        capture_output=True,
        text=True,
        env=env,
        timeout=60,
    )
    return time.monotonic() - t0


def _ids(entries: tuple[CorpusEntry, ...]) -> list[str]:
    return [e.cid for e in entries]


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("entry", BASELINE_CORPUS, ids=_ids(BASELINE_CORPUS))
def test_wall_clock_within_envelope(entry: CorpusEntry, tmp_path):
    """Median wall-clock for *entry* must not exceed committed_p50 * tolerance_factor."""
    envelope = load_runtime_envelope()
    by_cid = {rec["cid"]: rec for rec in envelope.get("entries", [])}

    if entry.cid not in by_cid:
        pytest.skip(reason=f"baseline_missing: no committed timing for {entry.cid!r}")

    committed_p50: float = by_cid[entry.cid]["wall_clock_seconds_p50"]
    tolerance_pct: float = (envelope.get("tolerance") or {}).get("wall_clock_pct", _TOLERANCE_FALLBACK_PCT)
    tolerance_factor = 1.0 + tolerance_pct / 100.0
    limit = committed_p50 * tolerance_factor

    palace = entry.builder(tmp_path)
    args = ["--json-output", entry.pipeline, str(palace)]

    samples = [_wall_clock_run(args) for _ in range(N_PERF_RUNS)]
    live_p50 = median(samples)

    assert live_p50 <= limit, (
        f"[{entry.cid}] wall-clock regression: "
        f"live_p50={live_p50:.3f}s > limit={limit:.3f}s "
        f"(committed_p50={committed_p50:.3f}s × {tolerance_factor:.2f})"
    )
